<?php

namespace AppBundle\Repository;

use AppBundle\Repository\base\BaseRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseRepository
{
    public function getArticlesWithComment()
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->leftJoin('a.comments', 'c')
            ->addSelect('c');

        return $qb->getQuery()->getResult();
    }
}
