<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends EntityRepository
{
    public function badgeUnlockAndNotUsed($actionName, $actionCount, $userId)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.actionName = :actionName')
            ->andWhere('b.actionCount = :actionCount')
            ->andWhere('u.user = :userId OR u.user IS NULL')
            ->leftJoin('b.unlockBadge', 'u')
            ->setParameter(':actionName', $actionName)
            ->setParameter(':actionCount', $actionCount)
            ->setParameter(':userId', $userId);

        return $qb->getQuery()->getSingleResult();
    }

    public function findBadgeFor($userId)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->join('b.unlockBadge', 'u')
            ->where('u.user = :userId')
            ->setParameter(':userId', $userId);

        return $qb->getQuery()->getArrayResult();
    }
}
