<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $articleId
     * @return string
     * @internal param int $userId
     */
    public function getCountComment(int $articleId) : string
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('COUNT(c)')
            ->where('c.article = :articleId')
            ->setParameter(':articleId', $articleId);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
