<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $userId
     */
    public function commentForUser($userId)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('COUNT(c)')
            ->where('c.author = :userId')
            ->setParameter(':userId', $userId);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
