<?php

namespace AppBundle\Repository;

/**
 * UnlockBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnlockBadgeRepository extends \Doctrine\ORM\EntityRepository
{
}
