<?php

namespace App\Repository;

use App\Entity\Comment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Comment::class);
    }

    /**
     * @param int $articleId
     *
     * @return string
     *
     * @internal param int $userId
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCountComment(int $articleId): string
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('COUNT(c)')
            ->where('c.article = :articleId')
            ->setParameter(':articleId', $articleId);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
